end/forms/app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('task/', views.index, name="index"),
    path('task/add', views.add, name="add")
]

end/forms/app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.


def index(request):
    # check if there already exists a session

    if "tasks" not in request.session:

        # If not, create a new list
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        # Access the data that the user submitted
        form = NewTaskForm(request.POST)

        # Check the validity of the form
        if form.is_valid():
            # Fetch the task from the clean version of the form
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]

            # redirect the user to listen for tasks
            return HttpResponseRedirect(reverse('app:index'))
        else:
            # If the form is invalid, re-render the page with existing information
            return render(request, 'tasks/add.html', {
                'form': form})
    return render(request, 'tasks/add.html', {
        'form': NewTaskForm()
    })


class NewTaskForm(forms.Form):
    task = forms.CharField(label='New Task')

end/forms/app/templates/tasks/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Task</title>
</head>
<body>
    <h3>Add Task</h3>
    <form action="{% url 'app:add' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <a href="{% url 'app:index' %}">View tasks</a>

</body>
</html>

end/forms/app/templates/tasks/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hiii</title>
</head>
<body>
    <h2>TODO list:</h2>
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'app:add' %}">add tasks</a>
    <br>
    <img src="{% static 'itachi.jpeg' %}" style="height: 500px; width: 500px;" alt="">
</body>
</html>